.PHONY: all clean
	
all: DatabaseController DatabaseController5 DatabaseControllerZ

DatabaseController: DatabaseController.java
	javac DatabaseController.java 

DatabaseController5: DatabaseController5.java
	javac DatabaseController5.java

DatabaseControllerZ: DatabaseControllerZ.java
	javac DatabaseControllerZ.java

clean:
	rm *.class